# This file is part of ansible-openvpn-server.
# Copyright (C) 2015 Leo Gaspard
#
# ansible-openvpn-server is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ansible-openvpn-server is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ansible-openvpn-server.  If not, see <http://www.gnu.org/licenses/>.
---

- name: "create pki directory"
  file:
      owner: "root"
      group: "root"
      mode: 0755
      path: "{{openvpn_server_home}}/pki"
      state: "directory"

- name: "secure private directory"
  file:
      owner: "root"
      group: "root"
      mode: 0700
      path: "{{openvpn_server_home}}/pki/private"
      state: "directory"

- name: "generate ca key"
  command: "/usr/bin/openssl req -nodes -newkey {{openvpn_server_ca_gen}} -keyout private/ca.key -out ca-csr.pem -subj '/CN={{openvpn_server_ca_cn}}/'"
  args:
      chdir: "{{openvpn_server_home}}/pki"
      creates: "private/ca.key"

- name: "sign ca key"
  command: "/usr/bin/openssl x509 -req -in ca-csr.pem -out ca.crt -CAcreateserial -signkey private/ca.key"
  args:
      chdir: "{{openvpn_server_home}}/pki"
      creates: "ca.crt"

- name: "remove temporary ca certificate signing request"
  file: "path={{openvpn_server_home}}/pki/ca-csr.pem state=absent"

- name: "protect ca key"
  file: "path={{openvpn_server_home}}/pki/private/ca.key mode=0400"

- name: "generate server key"
  command: "/usr/bin/openssl req -nodes -newkey {{openvpn_server_key_gen}} -keyout private/{{inventory_hostname}}.key -out {{inventory_hostname}}-csr.pem -subj '/CN={{openvpn_server_key_cn}}/'"
  args:
      chdir: "{{openvpn_server_home}}/pki"
      creates: "private/{{inventory_hostname}}.key"

- name: "sign server key"
  command: "/usr/bin/openssl x509 -req -in {{inventory_hostname}}-csr.pem -out {{inventory_hostname}}.crt -CA ca.crt -CAkey private/ca.key"
  args:
      chdir: "{{openvpn_server_home}}/pki"
      creates: "{{inventory_hostname}}.crt"

- name: "remove temporary server certification signing request"
  file: "path={{openvpn_server_home}}/pki/{{inventory_hostname}}-csr.pem state=absent"

- name: "generate tls auth key"
  command: "/usr/sbin/openvpn --genkey --secret ta.key"
  args:
      chdir: "{{openvpn_server_home}}"
      creates: "ta.key"

- name: "generate diffie-hellman parameters"
  command: "/usr/bin/openssl dhparam -out dh.pem {{openvpn_server_dh_size}}"
  args:
      chdir: "{{openvpn_server_home}}"
      creates: "dh.pem"
